openapi: 3.0.0
info:
  version: 1.0.0
  title: Connect 4 API
  description: An API to play the game Connect 4

paths:
  /game:
    post:
      summary: Start a new game
      operationId: startNewGame
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  winner:
                    type: string
                    description: The name of the winning player or "draw" if it's a tie
                  state:
                    type: string
                    description: The latest state of the game board
              examples:
                GameEndedInDraw:
                  summary: Game ended in a draw
                  value:
                    winner: "draw"
                    state: "⚫⚫⚫⚫⚫⚫⚫\n⚫⚫⚫⚫⚫⚫⚫\n⚫⚫⚫⚫⚫⚫⚫\n⚫🔴🟡🔴⚫⚫⚫\n⚫🔴🟡🟡🔴⚫⚫\n🔴🟡🟡🔴🟡🔴⚫"
        '400':
          description: Error occurred
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message

components:
  schemas:
    Game:
      type: object
      properties:
        winner:
          type: string
          description: The name of the winning player or "draw" if it's a tie
        state:
          type: string
          description: The latest state of the game board
